### ISSUE TITLE
友链

### ISSUE THREAD

**Issue by Gahotx** [Gahotx/comment#2]
https://gahotx.cn/#/friend

**Comment by yife68** [comment]
爱吃肉的猫更换网站icon图标
最新icon图标链接为：https://s1.ax1x.com/2023/05/26/p9qChjI.jpg

**Comment by Gahotx** [comment]
> @yife68
> 爱吃肉的猫更换网站icon图标
> 最新icon图标链接为：https://s1.ax1x.com/2023/05/26/p9qChjI.jpg

友链的图片我都存在自己的云存储了，问题不大

**Comment by AdingApkgg** [comment]
已加贵站😁
```yaml
- name: Asuna
  link: https://saop.cc/
  avatar: https://picbed.saop.cc/Asuna/Asuna1x1.png
  descr: 我们终会相遇相知，在那悠远的苍穹
```
